In [1]:
import pandas as pd

df1=pd.read_excel('Initial Data\Central Ludhiana_Revised.xlsx',index_col=0,sheet_name=1, usecols="A:B,D:O",skiprows=1)
df1.rename(columns = {' ':'Age','Unnamed: 1':'Farm Size','Unnamed: 3':'Age', 'Unnamed: 10':'Parity/Lactation no.','Unnamed: 11':'Milk production per day','Unnamed: 12':'Age of 1st Calving','Unnamed: 13':'Milking months','Unnamed: 14':'Dry months'},inplace=True)
df1['Murah'] = df1['Murah'].astype(str).str.replace("1","Murah")
df1['Murah'] = df1['Murah'].astype(str).str.replace("0","")
df1['N.R.'] = df1['N.R.'].astype(str).str.replace("1","N.R.")
df1['N.R.'] = df1['N.R.'].astype(str).str.replace("0","")
df1['H.F'] = df1['H.F'].astype(str).str.replace("1","H.F")
df1['H.F'] = df1['H.F'].astype(str).str.replace("0","")
df1['Jersi'] = df1['Jersi'].astype(str).str.replace("1","Jersi")
df1['Jersi'] = df1['Jersi'].astype(str).str.replace("0","")
df1['Sahiwal'] = df1['Sahiwal'].astype(str).str.replace("1","Sahiwal")
df1['Sahiwal'] = df1['Sahiwal'].astype(str).str.replace("0","")
df1['Brown'] = df1['Brown'].astype(str).str.replace("1","Brown")
df1['Brown'] = df1['Brown'].astype(str).str.replace("0","")

df2=pd.read_excel('Initial Data\Central Sangrur_Revised.xlsx',index_col=0,sheet_name=1, usecols="A:B,D:O",skiprows=1)
df2.rename(columns = {' ':'Age','Unnamed: 1':'Farm Size','Unnamed: 3':'Age', 'Unnamed: 10':'Parity/Lactation no.','Unnamed: 11':'Milk production per day','Unnamed: 12':'Age of 1st Calving','Unnamed: 13':'Milking months','Unnamed: 14':'Dry months'},inplace=True)
df2['Murah'] = df2['Murah'].astype(str).str.replace("1","Murah")
df2['Murah'] = df2['Murah'].astype(str).str.replace("0","")
df2['N.R.'] = df2['N.R.'].astype(str).str.replace("1","N.R.")
df2['N.R.'] = df2['N.R.'].astype(str).str.replace("0","")
df2['H.F'] = df2['H.F'].astype(str).str.replace("1","H.F")
df2['H.F'] = df2['H.F'].astype(str).str.replace("0","")
df2['Jersi'] = df2['Jersi'].astype(str).str.replace("1","Jersi")
df2['Jersi'] = df2['Jersi'].astype(str).str.replace("0","")
df2['Sahiwal'] = df2['Sahiwal'].astype(str).str.replace("1","Sahiwal")
df2['Sahiwal'] = df2['Sahiwal'].astype(str).str.replace("0","")
df2['Brown'] = df2['Brown'].astype(str).str.replace("1","Brown")
df2['Brown'] = df2['Brown'].astype(str).str.replace("0","")

df3=pd.read_excel('Initial Data\SM Gurdaspur_Revised.xlsx',index_col=0,sheet_name=1, usecols="A:B,D:O",skiprows=1)
df3.rename(columns = {' ':'Age','Unnamed: 1':'Farm Size','Unnamed: 3':'Age', 'Unnamed: 10':'Parity/Lactation no.','Unnamed: 11':'Milk production per day','Unnamed: 12':'Age of 1st Calving','Unnamed: 13':'Milking months','Unnamed: 14':'Dry months'},inplace=True)
df3['Murah'] = df3['Murah'].astype(str).str.replace("1","Murah")
df3['Murah'] = df3['Murah'].astype(str).str.replace("0","")
df3['N.R.'] = df3['N.R.'].astype(str).str.replace("1","N.R.")
df3['N.R.'] = df3['N.R.'].astype(str).str.replace("0","")
df3['H.F'] = df3['H.F'].astype(str).str.replace("1","H.F")
df3['H.F'] = df3['H.F'].astype(str).str.replace("0","")
df3['Jersi'] = df3['Jersi'].astype(str).str.replace("1","Jersi")
df3['Jersi'] = df3['Jersi'].astype(str).str.replace("0","")
df3['Sahiwal'] = df3['Sahiwal'].astype(str).str.replace("1","Sahiwal")
df3['Sahiwal'] = df3['Sahiwal'].astype(str).str.replace("0","")
df3['Brown'] = df3['Brown'].astype(str).str.replace("1","Brown")
df3['Brown'] = df3['Brown'].astype(str).str.replace("0","")

df4=pd.read_excel('Initial Data\SM Hoshiarpur_Revised.xlsx',index_col=0,sheet_name=1, usecols="A:B,D:O",skiprows=1)
df4.rename(columns = {' ':'Age','Unnamed: 1':'Farm Size','Unnamed: 3':'Age', 'Unnamed: 10':'Parity/Lactation no.','Unnamed: 11':'Milk production per day','Unnamed: 12':'Age of 1st Calving','Unnamed: 13':'Milking months','Unnamed: 14':'Dry months'},inplace=True)
df4['Murah'] = df4['Murah'].astype(str).str.replace("1","Murah")
df4['Murah'] = df4['Murah'].astype(str).str.replace("0","")
df4['N.R.'] = df4['N.R.'].astype(str).str.replace("1","N.R.")
df4['N.R.'] = df4['N.R.'].astype(str).str.replace("0","")
df4['H.F'] = df4['H.F'].astype(str).str.replace("1","H.F")
df4['H.F'] = df4['H.F'].astype(str).str.replace("0","")
df4['Jersi'] = df4['Jersi'].astype(str).str.replace("1","Jersi")
df4['Jersi'] = df4['Jersi'].astype(str).str.replace("0","")
df4['Sahiwal'] = df4['Sahiwal'].astype(str).str.replace("1","Sahiwal")
df4['Sahiwal'] = df4['Sahiwal'].astype(str).str.replace("0","")
df4['Brown'] = df4['Brown'].astype(str).str.replace("1","Brown")
df4['Brown'] = df4['Brown'].astype(str).str.replace("0","")

df5=pd.read_excel('Initial Data\SW Muktsar_Revised.xlsx',index_col=0,sheet_name=1, usecols="A:B,D:O",skiprows=1)
df5.rename(columns = {' ':'Age','Unnamed: 1':'Farm Size','Unnamed: 3':'Age', 'Unnamed: 10':'Parity/Lactation no.','Unnamed: 11':'Milk production per day','Unnamed: 12':'Age of 1st Calving','Unnamed: 13':'Milking months','Unnamed: 14':'Dry months'},inplace=True)
df5['Murah'] = df5['Murah'].astype(str).str.replace("1","Murah")
df5['Murah'] = df5['Murah'].astype(str).str.replace("0","")
df5['N.R.'] = df5['N.R.'].astype(str).str.replace("1","N.R.")
df5['N.R.'] = df5['N.R.'].astype(str).str.replace("0","")
df5['H.F'] = df5['H.F'].astype(str).str.replace("1","H.F")
df5['H.F'] = df5['H.F'].astype(str).str.replace("0","")
df5['Jersi'] = df5['Jersi'].astype(str).str.replace("1","Jersi")
df5['Jersi'] = df5['Jersi'].astype(str).str.replace("0","")
df5['Sahiwal'] = df5['Sahiwal'].astype(str).str.replace("1","Sahiwal")
df5['Sahiwal'] = df5['Sahiwal'].astype(str).str.replace("0","")
df5['Brown'] = df5['Brown'].astype(str).str.replace("1","Brown")
df5['Brown'] = df5['Brown'].astype(str).str.replace("0","")

frames = [df1, df2, df3, df4, df5]
result = pd.concat(frames)

result["Breed"] = result['Murah'].astype(str) +result['N.R.'].astype(str)+ result['H.F'].astype(str)+result['Jersi'].astype(str)+result['Sahiwal'].astype(str)+result['Brown'].astype(str)
result=result.drop(['Murah'], axis=1)
result=result.drop(['N.R.'], axis=1)
result=result.drop(['H.F'], axis=1)
result=result.drop(['Jersi'], axis=1)
result=result.drop(['Sahiwal'], axis=1)
result=result.drop(['Brown'], axis=1)
result["Milk Production/Day"]=result['Milk production per day'].astype(str)
result=result.drop(['Milk production per day'], axis=1)

result=result.fillna(method='ffill')

excelpath = 'Processed Data\Intrinsic Data.xlsx'
with pd.ExcelWriter(excelpath) as writer:
    result.to_excel(writer,sheet_name='Sheet1')